# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - svfr-iot-fullstack-webapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  WEBAPI_PROJECT_FILE: './IotPlatformDemo.API/IotPlatformDemo.API.csproj'
  FUNCTIONS_PROJECT_FILE: './IotPlatformDemo.Functions/IotPlatformDemo.Functions.csproj'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build solution with dotnet
        run: dotnet build

      - name: Test with dotnet
        run: dotnet test --no-build --logger trx

      - name: generate test report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: Tests           
          path: IotPlatformDemo.Tests/TestResults/*.trx 
          reporter: dotnet-trx

      - name: dotnet publish api
        run: dotnet publish ${{ env.WEBAPI_PROJECT_FILE }} -c Release -o ${{env.DOTNET_ROOT}}/api

      - name: upload api artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-api
          path: ${{env.DOTNET_ROOT}}/api
          
      - name: dotnet publish functions
        run: dotnet publish ${{ env.FUNCTIONS_PROJECT_FILE }} -c Release -o ${{env.DOTNET_ROOT}}/functions

      - name: upload functions artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-functions
          path: ${{env.DOTNET_ROOT}}/functions    

  deploy-api:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-api
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB4986D716F24567A38B3F982C91BB70 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A7DF7185924D4F66881567489550CCFB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E9B21F2C2682402FBFE06A022EE29F3A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'svfr-iot-fullstack-webapi'
          slot-name: 'Production'
          package: .
          clean: true
    
  deploy-functions:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-functions

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AB4986D716F24567A38B3F982C91BB70 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A7DF7185924D4F66881567489550CCFB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E9B21F2C2682402FBFE06A022EE29F3A }}

      - name: Deploy to Azure
        id: fa
        uses: Azure/functions-action@v1
        with:
          app-name: 'svfr-iot-fullstack-functions'
          slot-name: 'Production'
          package: .
          clean: true        
          